theme: jekyll-theme-minimal
title: Homepage Germanistentag22 Panel "Weder Fail noch Lobgesang: Nicht-eindeutige Wertung von Literatur im Digitalen Raum"
logo: assets/pics/stars.jpg
description: "pic by Towfiqu barbhuiya (unsplash)"
